version: "3"

services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "472:472:0755:/var/data/prometheus/data"
    volumes:
      - "./prom-data:/var/data"

  prometheus:
    image: prom/prometheus
    command: ['--config.file=/pingprom/prometheus.yml']
    ports: ['9090:9090']
    volumes:
      - ./prom-data:/prometheus/data
      - ./prometheus:/pingprom/

  blackbox:
    privileged: true
    image: prom/blackbox-exporter
    command: ['--config.file=/config/blackbox.yml']
    ports: ['9115:9115']
    volumes: ['./blackbox.yml:/config/blackbox.yml']

  alertmanager:
    image: prom/alertmanager
    command: ['--config.file=/alertmanager.yml']
    ports: ['9093:9093']
    volumes: ['./alertmanager.yml:/alertmanager.yml']

  grafana: # https://grafana.com/docs/installation/docker/#configuration
    image: grafana/grafana
    ports: ['3000:3000']
    volumes:
      - ./grafana-data:/var/lib/grafana
